---
# - name: Enabling YEdit
#   ansible.builtin.import_role:
#     name: kwoodson.yedit
- name: Ensure Netplan file has correct permissions and ownership
  ansible.builtin.file:
    path: "{{ netplan_config_interface_netplanfile }}"
    owner: root
    group: root
    mode: "0600"
- name: Setting MTU
  nerdynik.general.yedit:
    src: "{{ netplan_config_interface_netplanfile }}"
    key: "network.ethernets.{{ netplan_config_interface_interface }}.mtu"
    value: "{{ netplan_config_interface_mtu }}"
  notify: netplan apply
- name: Setting DHCP4
  nerdynik.general.yedit:
    src: "{{ netplan_config_interface_netplanfile }}"
    key: "network.ethernets.{{ netplan_config_interface_interface }}.dhcp4"
    value: "{{ netplan_config_interface_dhcp4 }}"
  notify: netplan apply
- name: Setting Static IPv4 - Addresses
  when: not netplan_config_interface_dhcp4
  nerdynik.general.yedit:
    src: "{{ netplan_config_interface_netplanfile }}"
    key: "network.ethernets.{{ netplan_config_interface_interface }}.addresses"
    value: "{{ netplan_config_interface_ip4_addresses }}"
  notify: netplan apply
- name: Setting Static IPv4 - Routes
  when: not netplan_config_interface_dhcp4
  nerdynik.general.yedit:
    src: "{{ netplan_config_interface_netplanfile }}"
    key: "network.ethernets.{{ netplan_config_interface_interface }}.routes"
    value: "{{ netplan_config_interface_ip4_routes }}"
  notify: netplan apply
- name: Setting Static IPv4 - Routes
  when: netplan_config_interface_dns4_addresses | length > 0
  nerdynik.general.yedit:
    src: "{{ netplan_config_interface_netplanfile }}"
    key: "network.ethernets.{{ netplan_config_interface_interface }}.nameservers.addresses"
    value: "{{ netplan_config_interface_dns4_addresses }}"
  notify: netplan apply
